definitions:
  api.LoginResponse:
    properties:
      data:
        properties:
          CreatedAt:
            type: string
          DeletedAt:
            type: string
          ID:
            type: integer
          UpdatedAt:
            type: string
          student_id:
            type: string
          token:
            type: string
          username:
            type: string
        type: object
    type: object
  api.RegisterResponse:
    properties:
      data:
        properties:
          ID:
            type: integer
          username:
            type: string
        type: object
    type: object
info:
  contact: {}
  description: 后端api接口文档
  title: 小航书后端
  version: 0.0.1
paths:
  /api/v1/public/login:
    post:
      description: 登录接口，返回用户信息与token
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: 登录成功结果
          schema:
            $ref: '#/definitions/api.LoginResponse'
        "400":
          description: 登录失败
          schema:
            type: object
      summary: 用户登录
      tags:
      - 公共接口
  /api/v1/public/register:
    post:
      description: 注册时需要先发送验证码，这里传入的 username 其实就是学号，创建账号成功后默认的初始 username 也即学号
      parameters:
      - description: 用户名（学号）
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 发送的验证码（有效期内）
        in: body
        name: code
        required: true
        schema:
          type: string
      responses:
        "200":
          description: 注册成功结果
          schema:
            $ref: '#/definitions/api.RegisterResponse'
        "400":
          description: 注册失败
          schema:
            type: object
      summary: 用户注册
      tags:
      - 公共接口
  /api/v1/public/send-email:
    post:
      description: 验证码存在 redis 里，默认配置5min，对学号拼接 @buaa.edu.cn 发送
      parameters:
      - description: 学号
        in: body
        name: student_id
        required: true
        schema:
          type: string
      responses:
        "500":
          description: 服务器端验证码发送失败，可能是邮箱不对或服务问题
          schema:
            type: object
      summary: 发送验证码
      tags:
      - 公共接口
  /ping:
    post:
      description: ping通此接口，说明项目运行成功
      responses:
        "200":
          description: 连接成功
          schema:
            type: string
      summary: 测试连接
swagger: "2.0"
